server:
  port: 8080
  compression:
    min-response-size: 4096    
  

spring:
  application:
    name: diseno-sistemas  # Service registers under this name
      
     #Datasource and JPA configuration
  datasource:
    url: jdbc:mysql://localhost:3306/diseno_sistemas
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      
liquibase:
  context: production